version: "3.8"

networks:
  monitor:
    driver: bridge
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.99.0
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel-collector.yaml
    networks:
      - monitor

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.2
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
     # 要使用 prometheus 的api : api/v1/write時要加入此行
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    networks:
      - monitor

  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml

    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    networks:
      - monitor

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      #- ./tempo-data:/var/tempo
    ports:
      - "3200"   # tempo
      - "4400:4317"
    depends_on:
      - init
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    # volumes:
    #   - ./loki-config.yaml:/etc/loki/local-config.yaml
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor