receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  logging:
    verbosity: normal
  otlp/tempo:
    endpoint: tempo:4400
    tls:
      insecure: true
  loki:
    endpoint: loki_host/loki/api/v1/push
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
    timeout: 1s
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  resource/loki:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace, service.version, ApplicationName

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      exporters: [loki]
      processors: [resource/loki]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]