  scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "web-app"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: ["web-app:8080"]

  - job_name: "otel-collector"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: ["otel-collector:8888"]
      
  - job_name: "tempo"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: ["tempo:58789"]